### ISSUE TITLE
Command-level descriptions

### ISSUE THREAD

**Issue by nergal-perm** [Decision-Driven-Development/logic-checker#17]
Add a special optional section to the command files. Something like:
```yaml
description:
  summary: "This is a command that initializes a state for an application"
  arguments:
    - name: "startingPlayer"
      type: "string"
      description: "The id of the first player to make a move"
```

The description like that can be used as a documentation, and it also can be presented in a Logic Checker WebUI tool to provide the context for the designer or user.
